CREATE TABLE "WEATHER_GROUP_REL"
(	"WEATHER_ID" NUMBER NOT NULL,
"RESEARCH_GROUP_ID" NUMBER NOT NULL,
CONSTRAINT "REL_WEATHER_GROUP_PK" PRIMARY KEY("WEATHER_ID","RESEARCH_GROUP_ID"),
CONSTRAINT "REL_WEATHER_FK" FOREIGN KEY("WEATHER_ID") REFERENCES "WEATHER"("WEATHER_ID"),
CONSTRAINT "REL_WEATHER_GROUP_FK" FOREIGN KEY("RESEARCH_GROUP_ID") REFERENCES "RESEARCH_GROUP"("RESEARCH_GROUP_ID")
);

